$(document).ready(function()
        {
            $('#mycarousel').carousel({interval:2000});
            $('#carouselButton').click(function()
            {
                if($('#carouselButton').children('span').hasClass('fa-pause'))
                {
                    $('#mycarousel').carousel('pause');
                    $('#carouselButton').children('span').removeClass('fa-pause');
                    $('#carouselButton').children('span').addClass('fa-play');
                }
                else if($('#carouselButton').children('span').hasClass('fa-play'))
                {
                    $('#mycarousel').carousel('cycle');
                    $('#carouselButton').children('span').removeClass('fa-play');
                    $('#carouselButton').children('span').addClass('fa-pause');
                }
            });
        });

        $(document).ready(function()
        {
            $('#button').click(function()
            {
                $('#loginmodal').modal('show');
            });
            $('#close').click(function()
            {
                $('#loginmodal').modal('hide');
            });
            $('#cancel').click(function()
            {
                $('#loginmodal').modal('hide');
            });
        });

        $(document).ready(function()
        {
            $('#buttontable').click(function()
            {
                $('#reservemodal').modal('show');
            });
            $('#closetable').click(function()
            {
                $('#reservemodal').modal('hide');
            });
            $('#canceltable').click(function()
            {
                $('#reservemodal').modal('hide');
            });
        });